export const locations = [
  'Praha',
  'Brno',
  'Ostrava',
  'Plzeň',
  'Liberec',
  'Olomouc',
  'Ústí nad Labem',
  'Hradec Králové',
  'České Budějovice',
  'Pardubice',
  'Havířov',
  'Zlín',
  'Kladno',
  'Most',
  'Karviná',
  'Frýdek-Místek',
  'Opava',
]
